--!strict

return {
	NOP = 0,
	DIE_IF_HEALTH_NON_POSITIVE = 1,
	KNOCKBACK = 2,
	SQUISHED = 3,
	SPECIAL_KOOPA_LOSE_SHELL = 4,
	SET_SPEED_TO_ZERO = 5,
	SPECIAL_WIGGLER_JUMPED_ON = 6,
	SPECIAL_HUGE_GOOMBA_WEAKLY_ATTACKED = 7,
	SQUISHED_WITH_BLUE_COIN = 8,
}
